# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8391e4b5057110f39a666fb929fd85e8477feadad09bd3c5c48296fac834890e8f40ac2c989459a7aab730ab80b037b08446593bbeb976777e92b5058aab685

test:
  secret_key_base: 7440e49dfb9829ea6425c86ec600cf7c7c4d58b3f52cf462278f9602ea021a6db7b0a129cd38a24bd6662e5d0be8c9658e376d345d33a92b732b9fffed344c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
